export const HTTP_STATUSES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFILCT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const HTTP_MESSAGES = {
  [HTTP_STATUSES.OK]: "OK",
  [HTTP_STATUSES.CREATED]: "CREATED",
  [HTTP_STATUSES.ACCEPTED]: "ACCEPTED",
  [HTTP_STATUSES.BAD_REQUEST]: "Bad Request",
  [HTTP_STATUSES.UNAUTHORIZED]: "Unauthorized",
  [HTTP_STATUSES.FORBIDDEN]: "Forbidden",
  [HTTP_STATUSES.NOT_FOUND]: "Not Found",
  [HTTP_STATUSES.CONFILCT]: "Conflict",
  [HTTP_STATUSES.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
  [HTTP_STATUSES.INTERNAL_SERVER_ERROR]: "Internal Server Error",
  [HTTP_STATUSES.SERVICE_UNAVAILABLE]: "Service unavailable",
};
